// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {port} from '../models';

export function DeleteAgent(arg1:string):Promise<void>;

export function GetActiveAgent():Promise<port.AgentConfig>;

export function GetAgents():Promise<Array<port.AgentConfig>>;

export function SaveAgent(arg1:port.AgentConfig):Promise<port.AgentConfig>;

export function SetActiveAgent(arg1:string):Promise<void>;
