// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAgent(arg1) {
  return window['go']['main']['AgentBind']['DeleteAgent'](arg1);
}

export function GetActiveAgent() {
  return window['go']['main']['AgentBind']['GetActiveAgent']();
}

export function GetAgents() {
  return window['go']['main']['AgentBind']['GetAgents']();
}

export function SaveAgent(arg1) {
  return window['go']['main']['AgentBind']['SaveAgent'](arg1);
}

export function SetActiveAgent(arg1) {
  return window['go']['main']['AgentBind']['SetActiveAgent'](arg1);
}
