// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SendText(arg1) {
  return window['go']['main']['App']['SendText'](arg1);
}
