// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel():Promise<void>;

export function GetVersion():Promise<string>;

export function Quit():Promise<void>;

export function SendText(arg1:string):Promise<void>;
