// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {port} from '../models';

export function Cancel():Promise<void>;

export function DownloadSTTModel():Promise<void>;

export function GetAudioDevices():Promise<Array<port.AudioDevice>>;

export function GetOllamaModels():Promise<Array<string>>;

export function GetSTTModelStatus():Promise<port.STTModelStatus>;

export function GetVersion():Promise<string>;

export function IsListening():Promise<boolean>;

export function Quit():Promise<void>;

export function SendText(arg1:string):Promise<void>;

export function SetAudioDevice(arg1:string):Promise<void>;

export function StartListening():Promise<void>;

export function StopListening():Promise<void>;
