// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function DownloadSTTModel() {
  return window['go']['main']['App']['DownloadSTTModel']();
}

export function GetAudioDevices() {
  return window['go']['main']['App']['GetAudioDevices']();
}

export function GetOllamaModels() {
  return window['go']['main']['App']['GetOllamaModels']();
}

export function GetSTTModelStatus() {
  return window['go']['main']['App']['GetSTTModelStatus']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IsListening() {
  return window['go']['main']['App']['IsListening']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SendText(arg1) {
  return window['go']['main']['App']['SendText'](arg1);
}

export function SetAudioDevice(arg1) {
  return window['go']['main']['App']['SetAudioDevice'](arg1);
}

export function StartListening() {
  return window['go']['main']['App']['StartListening']();
}

export function StopListening() {
  return window['go']['main']['App']['StopListening']();
}
