// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAudioDevices() {
  return window['go']['main']['AudioBind']['GetAudioDevices']();
}

export function IsListening() {
  return window['go']['main']['AudioBind']['IsListening']();
}

export function SetAudioDevice(arg1) {
  return window['go']['main']['AudioBind']['SetAudioDevice'](arg1);
}

export function StartListening() {
  return window['go']['main']['AudioBind']['StartListening']();
}

export function StopListening() {
  return window['go']['main']['AudioBind']['StopListening']();
}
