// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {port} from '../models';

export function GetAudioDevices():Promise<Array<port.AudioDevice>>;

export function IsListening():Promise<boolean>;

export function SetAudioDevice(arg1:string):Promise<void>;

export function StartListening():Promise<void>;

export function StopListening():Promise<void>;
