// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RegisterHotkey(arg1:string,arg2:Array<string>):Promise<void>;

export function UnregisterHotkey(arg1:string):Promise<void>;
