// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RegisterHotkey(arg1, arg2) {
  return window['go']['main']['HotkeysBind']['RegisterHotkey'](arg1, arg2);
}

export function UnregisterHotkey(arg1) {
  return window['go']['main']['HotkeysBind']['UnregisterHotkey'](arg1);
}
