// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelResponse():Promise<void>;

export function SendText(arg1:string):Promise<void>;
