// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelResponse() {
  return window['go']['main']['LLMBind']['CancelResponse']();
}

export function SendText(arg1) {
  return window['go']['main']['LLMBind']['SendText'](arg1);
}
