// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {port} from '../models';

export function DownloadSTTModel():Promise<void>;

export function GetSTTModelStatus():Promise<port.STTModelStatus>;
