// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadSTTModel() {
  return window['go']['main']['ModelsBind']['DownloadSTTModel']();
}

export function GetSTTModelStatus() {
  return window['go']['main']['ModelsBind']['GetSTTModelStatus']();
}
