// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {port} from '../models';

export function GetOverlayMode():Promise<port.OverlayMode>;

export function HideOverlay():Promise<void>;

export function SetOverlayMode(arg1:port.OverlayMode):Promise<void>;

export function ShowOverlay():Promise<void>;
