// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOverlayMode() {
  return window['go']['main']['OverlayBind']['GetOverlayMode']();
}

export function HideOverlay() {
  return window['go']['main']['OverlayBind']['HideOverlay']();
}

export function SetOverlayMode(arg1) {
  return window['go']['main']['OverlayBind']['SetOverlayMode'](arg1);
}

export function ShowOverlay() {
  return window['go']['main']['OverlayBind']['ShowOverlay']();
}
