// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPermissionStatus(arg1) {
  return window['go']['main']['PermissionsBind']['GetPermissionStatus'](arg1);
}

export function OpenPermissionSettings(arg1) {
  return window['go']['main']['PermissionsBind']['OpenPermissionSettings'](arg1);
}

export function RequestPermission(arg1) {
  return window['go']['main']['PermissionsBind']['RequestPermission'](arg1);
}
