// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {port} from '../models';

export function GetPermissionStatus(arg1:port.Permission):Promise<boolean>;

export function OpenPermissionSettings(arg1:port.Permission):Promise<void>;

export function RequestPermission(arg1:port.Permission):Promise<boolean>;
