// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureAndOCR(arg1) {
  return window['go']['main']['ScreenshotBind']['CaptureAndOCR'](arg1);
}

export function CaptureFullScreen() {
  return window['go']['main']['ScreenshotBind']['CaptureFullScreen']();
}

export function CaptureRegion() {
  return window['go']['main']['ScreenshotBind']['CaptureRegion']();
}
