// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureAndOCR(arg1:string):Promise<string>;

export function CaptureFullScreen():Promise<void>;

export function CaptureRegion():Promise<void>;
