// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSession() {
  return window['go']['main']['SessionBind']['ClearSession']();
}

export function GetSession() {
  return window['go']['main']['SessionBind']['GetSession']();
}

export function NewSession() {
  return window['go']['main']['SessionBind']['NewSession']();
}
