// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {port} from '../models';

export function ClearSession():Promise<void>;

export function GetSession():Promise<port.Session>;

export function NewSession():Promise<port.Session>;
