// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {port} from '../models';

export function GetSettings():Promise<port.AppSettings>;

export function GetShortcuts():Promise<Array<port.Shortcut>>;

export function SaveSettings(arg1:port.AppSettings):Promise<void>;

export function UpdateShortcut(arg1:string,arg2:Array<string>):Promise<void>;
