// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings() {
  return window['go']['main']['SettingsBind']['GetSettings']();
}

export function GetShortcuts() {
  return window['go']['main']['SettingsBind']['GetShortcuts']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['SettingsBind']['SaveSettings'](arg1);
}

export function UpdateShortcut(arg1, arg2) {
  return window['go']['main']['SettingsBind']['UpdateShortcut'](arg1, arg2);
}
